# Generated by Django 5.1 on 2024-08-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParsingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='Введите ключевые слова, разделенные запятыми')),
                ('stopwords', models.TextField(help_text='Введите стоп-слова, разделенные запятыми')),
                ('google_sheet_name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vkgroup')),
            ],
        ),
    ]
