# Generated by Django 5.1 on 2024-08-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsingsettings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='vkgroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='parsingsettings',
            name='comment',
            field=models.BooleanField(default=True, verbose_name='Парсить комментарии'),
        ),
        migrations.AddField(
            model_name='parsingsettings',
            name='post',
            field=models.BooleanField(default=True, verbose_name='Парсить посты'),
        ),
    ]
