# Generated by Django 5.1 on 2024-08-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vkgroup_group_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingsettings',
            name='spam',
            field=models.BooleanField(default=True, verbose_name='Спам'),
        ),
    ]
