# Generated by Django 5.1 on 2024-08-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usertoken_daily_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkgroup',
            name='group_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
