# Generated by Django 5.1 on 2024-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_vkgroup_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsingsettings',
            name='google_sheet_name',
        ),
        migrations.RemoveField(
            model_name='parsingsettings',
            name='group',
        ),
        migrations.RemoveField(
            model_name='parsingsettings',
            name='spam',
        ),
        migrations.AddField(
            model_name='parsingsettings',
            name='google_sheet_file',
            field=models.FileField(blank=True, help_text='Загрузите файл json', null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='parsingsettings',
            name='interval',
            field=models.IntegerField(default=5, verbose_name='Интервал'),
        ),
        migrations.AddField(
            model_name='parsingsettings',
            name='pars_from',
            field=models.DateField(blank=True, null=True, verbose_name='Парсить с даты'),
        ),
    ]
