# Generated by Django 5.1 on 2024-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_parsingsettings_google_sheet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingsettings',
            name='table_name',
            field=models.CharField(blank=True, help_text='Введите название таблицы', max_length=255, null=True),
        ),

    ]
