# Generated by Django 5.1 on 2024-09-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_parsingsettings_table_name_spam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'VK аккаунт', 'verbose_name_plural': 'VK аккаунты'},
        ),
        migrations.AlterField(
            model_name='parsingsettings',
            name='google_sheet_file',
            field=models.FileField(blank=True, help_text='Загрузите файл json', null=True, upload_to='files/%Y/%m/%d/', verbose_name='google ключ'),
        ),
        migrations.AlterField(
            model_name='parsingsettings',
            name='keywords',
            field=models.TextField(help_text='Введите ключевые слова, разделенные запятыми', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='parsingsettings',
            name='stopwords',
            field=models.TextField(help_text='Введите стоп-слова, разделенные запятыми', verbose_name='Стоп слова'),
        ),
        migrations.AlterField(
            model_name='parsingsettings',
            name='table_name',
            field=models.CharField(blank=True, help_text='Введите название таблицы', max_length=255, null=True, verbose_name='Название таблицы'),
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='spam_groups', to='main.vkgroup', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Спам',
                'verbose_name_plural': 'Спам',
            },
        ),
    ]
