# Generated by Django 5.1 on 2024-09-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_usertoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingsettings',
            name='interval',
            field=models.IntegerField(default=5, help_text='Установите интервал минутах', verbose_name='Интервал'),
        ),
    ]
